semety/apps/api/urls.py
from rest_framework import routers
from django.conf.urls import url, include
from .serializers import ThreadList, TabList, InviteList

app_name = 'api'
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'tabs', TabList)
router.register(r'threads', ThreadList)
router.register(r'invites', InviteList)


urlpatterns = [
	url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

semety/apps/clients/urls.py
from django.urls import path
from .views import *

app_name = 'contacts'

urlpatterns = [
    path('', ClientList.as_view(), name='client_list'),
    path('add/', ClientCreate.as_view(), name='client_add'),
    path('<int:pk>/', ClientDetail.as_view(), name='client_detail'),
    path('<int:pk>/update/', ClientUpdate.as_view(), name='client_update'),
    path('<int:pk>/delete/', ClientDelete.as_view(), name='client_delete'),


    path('<int:client>/contact/add/', ContactCreate.as_view(), name='contact_add'),
    path('<int:client>/contact/<int:pk>/', ContactDetail.as_view(), name='contact_detail'),
    path('<int:client>/contact/<int:pk>/update/', ContactUpdate.as_view(), name='contact_update'),
    path('<int:client>/contact/<int:pk>/delete/', ContactDelete.as_view(), name='contact_delete'),


    path('<int:client>/contact/<int:pk>/add-memo/', ContactMemo.as_view(), name='contact_memo'),
    path('<int:client>/contact/<int:contact>/<int:pk>/update/', ContactMemoUpdate.as_view(), name='contact_memo_update'),
    path('<int:client>/contact/<int:contact>/<int:pk>/delete/', ContactMemoDelete.as_view(), name='contact_memo_delete'),

]

semety/apps/core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
import semety.apps.core.views as core_views

from .forms import LoginForm
from .views import *
app_name = "core"

urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'auth:login'}, name='logout'),


    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    path('activate/<str:uidb64>/<str:token>',core_views.activate, name='activate'),

]

semety/apps/site/urls.py
from django.conf.urls import url

app_name = 'site'
urlpatterns = [
    #url(r'^$', UserProfileDetail.as_view(), name='home'),
]

semety/urls.py
""" URL config for semety project. """

from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.views import generic
from django.conf.urls.static import static
from .utils.views import FrontendView
from .apps.site.views import Homepage, WelcomePage, FeebackForm, About, Legal, Contact, Explore
from semety.apps.core.views import signup

admin.autodiscover()

from django.contrib.contenttypes.views import shortcut
from django.contrib.auth.views import password_change_done


urlpatterns = [

    # Admin URLs.
    path('admin/password_change/done/', password_change_done, name='password_change_done'),
    path('admin/', admin.site.urls),
    path('register/', signup, name="register"),
    path('', include('social.apps.django_app.urls', namespace='social')),
    path('', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('feedback/', FeebackForm.as_view(), name='login'),

    path('about/', About.as_view(), name='about'),
    path('legal/', Legal.as_view(), name='legal'),
    path('contact/', Contact.as_view(), name='contact'),
    path('explore/', Explore.as_view(), name='explore'),

    #Homepage
    path('', Homepage.as_view()),
    path('welcome/', WelcomePage.as_view()),
    path('', include('semety.apps.workspace.urls', namespace='workspace')),
    path('settings/', include('semety.apps.core.urls', namespace='core')),
    path('network/', include('semety.apps.network.urls', namespace='network')),
    path('api/', include('semety.apps.api.urls', namespace='workspace')),
    #path('network/', include('semety.apps.teams.urls', namespace='team')),
    path('clients/', include('semety.apps.clients.urls', namespace='clients')),
    path('notifications/', include('semety.apps.notifications.urls', namespace='notifications')),
    path('site/', include('semety.apps.site.urls', namespace='site')),
    #path('', include('semety.apps.teams.urls', namespace='teams')),


    # Permalink redirection service.
    path('<slug:content_type_id>-<slug:object_id>/', shortcut, name='permalink_redirect'),


    path('favicon.ico', generic.RedirectView.as_view(permanent=True)),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        path('404/', generic.TemplateView.as_view(template_name='404.html')),
        path('500/', generic.TemplateView.as_view(template_name='500.html')),
        path('frontend/', FrontendView.as_view()),
        path('frontend/<slug:slug>/', FrontendView.as_view())
    ]

semety/apps/clients/models.py
from django.db import models
from semety.apps.core.models import Company
from sorl.thumbnail import ImageField



class AddressAbstract(models.Model):

    address_line_1 = models.CharField(
        max_length=200,
        null=True,
    )

    city = models.CharField(
        max_length=200,
        null=True,
    )

    county = models.CharField(
        max_length=200,
        null=True,
    )

    postal_code = models.CharField(
        max_length=200,
        null=True,
    )

    country = models.CharField(
        max_length=200,
        null=True,
    )


    def full_address(self):
        return self.address_line_1 + '\n' + self.city + '\n' + self.county + '\n' + self.postal_code + '\n' + self.country


    class Meta:
        abstract =True


class Client(AddressAbstract):

    name = models.CharField(
        max_length=200,
    )

    main_phone = models.CharField(
        max_length=200,
    )

    main_email = models.EmailField(
        max_length=200,
    )

    logo = ImageField(
        null=True,
        blank=True,
    )

    team = models.ForeignKey(
        Company,
        on_delete=models.PROTECT,
    )

    class Meta:
        ordering = ['name']

    @models.permalink
    def get_absolute_url(self):
            return ("clients:client_detail", (), {
                "pk": self.pk
            })


    @models.permalink
    def get_delete_url(self):
            return ("clients:client_delete", (), {
                "pk": self.pk,
            })


class Contact(models.Model):

    client = models.ForeignKey(
        Client,
        blank=True,
        on_delete=models.CASCADE,
    )

    full_name = models.CharField(
        max_length=200,
        null=True,
        )


    email = models.EmailField(
        max_length=400,
    )

    phone = models.CharField(
        max_length=300,
    )

    memo = models.TextField(
        null=True,
    )

    @property
    def memos(self):
        return self.contactmemo_set.all()


    @models.permalink
    def get_delete_url(self):
            return ("clients:contact_delete", (), {
                "client": self.client.pk,
                "pk": self.pk,
            })

    @models.permalink
    def get_absolute_url(self):
            return ("clients:contact_detail", (), {
                "client": self.client.pk,
                "pk": self.pk,
            })


class ContactMemo(models.Model):

    contact = models.ForeignKey(
        Contact,
        on_delete=models.CASCADE,
    )

    title = models.CharField(
        max_length=200,
        null=True,
    )

    text = models.TextField(
        null=True,
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
        null=True
    )

    @models.permalink
    def get_absolute_url(self):
            return ("clients:contact_detail", (), {
                "client": self.contact.client.pk,
                "pk": self.contact.pk,
            })


    @models.permalink
    def get_update_url(self):
            return ("clients:contact_memo_update", (), {
                "client": self.contact.client.pk,
                "contact": self.contact.pk,
                "pk": self.pk,
            })

    @models.permalink
    def get_delete_url(self):
            return ("clients:contact_memo_delete", (), {
                "client": self.contact.client.pk,
                "contact": self.contact.pk,
                "pk": self.pk,
            })

    @property
    def modal(self):
        return "memo_modal_" + str(self.pk)

    @property
    def plain_text(self):
        text = self.text
        tags_allowed = ["<h1>", "</h1>", "<h2>", "</h2>", "<h3>", "</h3>", "<h4>", "<h5>", "<h6>", "</h6>", "<div>", "</div>", "<br>", "<b>", "</b>", "<i>", "</i>", "<u>", "</u>"]
        for x in tags_allowed:
            text = text.replace(x, "")
        return text

    @property
    def revealSemetyText(self):
        return "revealSemetyText_memo_" + str(self.pk)

    @property
    def form(self):
        from .forms import ContactMemoForm
        return ContactMemoForm(instance=self)

semety/apps/api/views.py
from django.shortcuts import render

# Create your views here.

semety/apps/clients/views.py
from .models import Client, Contact, ContactMemo
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView
from django.views.generic.edit import ModelFormMixin
from .forms import ClientForm, ContactForm, ContactMemoForm
from django.urls import reverse





def GetUser(teammate):
    return teammate.user

class ClientList(ListView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_add_form'] = ClientForm
        return context

    def get_queryset(self):
        return Client.objects.filter(team=self.request.user.company)


class ClientDetail(DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_edit_form'] = ClientForm(instance=self.object)
        context['add_contact_form'] = ContactForm
        return context


class ClientCreate(CreateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        Form = form.save(commit=False)
        Form.user = self.request.user
        Form.team = self.request.user.company
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class ClientUpdate(UpdateView):
    model = Client
    form_class = ClientForm


class ClientDelete(DeleteView):
    model = Client

    def get_success_url(self):
        return reverse('clients:client_list', kwargs={})


#Contacts

class ContactDetail(DetailView):
    model = Contact

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['memo_form'] = ContactMemoForm
        context['contact_edit_form'] = ContactForm(instance=self.object)
        return context


class ContactDelete(DeleteView):
    model = Contact

    def get_success_url(self):
        return reverse('clients:client_detail', kwargs={'pk': self.kwargs['client']})


class ContactMemoUpdate(UpdateView):
    model = ContactMemo
    form_class = ContactMemoForm


class ContactMemoDelete(DeleteView):
    model = ContactMemo

    def get_success_url(self):
        return reverse('clients:contact_detail', kwargs={'client': self.kwargs['client'], 'pk': self.kwargs['contact']})


class ContactMemo(CreateView):
    model = ContactMemo
    form_class = ContactMemoForm

    def form_valid(self, form):
        Form = form.save(commit=False)
        Form.contact = Contact.objects.get(pk=self.kwargs['pk'])
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class ContactCreate(CreateView):
    model = Contact
    form_class = ContactForm

    def form_valid(self, form):
        Form = form.save(commit=False)
        Form.client = Client.objects.get(pk=self.kwargs['client'])
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class ContactUpdate(UpdateView):
    model = Contact
    form_class = ContactForm

semety/apps/core/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.views.generic import DetailView, UpdateView
from django.conf import settings
from .forms import SignUpForm
from .tokens import account_activation_token

User = get_user_model()


@login_required
def home(request):
    return render(request, 'core/home.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('core/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)

            return redirect('core:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'registration/register.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'core/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()
        login(request, user, backend=settings.AUTHENTICATION_BACKENDS[2])
        return redirect('workspace:tab_list')
    else:
        return render(request, 'core/account_activation_invalid.html')

semety/apps/network/views.py
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth import get_user_model
from ..core.models import Invite, Company, CompanyUser
from ..core.forms import UserForm, CompanyUserForm
from django.urls import reverse_lazy
from ..core.forms import UserInForm

User = get_user_model()


class UserProfile(DetailView):
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserForm(instance=self.object)
        return context

    def get_object(self):
        queryset = self.get_queryset()
        return queryset.get(pk=self.request.user.pk)


class UserProfileUpdate(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('network:profile')

    def get_object(self):
        queryset = self.get_queryset()
        return queryset.get(pk=self.request.user.pk)


class CompanyDetail(DetailView):
    model = Company

    def get_object(self):
        queryset = self.get_queryset()
        return queryset.get(pk=self.request.user.company.pk)


class CompanyUpdate(UpdateView):
    model = Company
    fields = "__all__"
    success_url = reverse_lazy('network:company_detail')

    def get_object(self):
        queryset = self.get_queryset()
        return queryset.get(pk=self.request.user.company.pk)


class CompanyUserUpdate(UserInForm, UpdateView):
    model = CompanyUser
    form_class = CompanyUserForm
    success_url = reverse_lazy('network:company_detail')

class CompanyInviteForm(CreateView):
    model = Invite
    fields = ('invite_to',)

    def form_valid(self, form):
        temp = form.save(commit=False)
        temp.invite_from = self.request.user
        temp.company = self.request.user.company
        temp.code = "testcode"
        return super().form_valid(form)


class CompanyInviteFormUpdate(UpdateView):
    model = Invite
    fields = ('invite_to',)


class CompanyInviteFormDelete(DeleteView):
    model = Invite
    success_url = reverse_lazy('network:company_detail')

semety/apps/notifications/views.py
from django.views.generic import ListView
from .models import Notification
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect

class NotificationList(ListView):
    model = Notification


def NotificationRead(request, pk):
    notification = get_object_or_404(
        Notification, user=request.user, id=pk)
    notification.read = True
    notification.save(send_email=False)

    return redirect(notification.model_instance.get_absolute_url())


def NotifcationMarkAllAsRead(request):
    for notifcation in Notification.objects.filter(user=request.user):
        notifcation.read = True
        notifcation.save(send_email=False)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

semety/utils/views.py
from django.views.generic import TemplateView


class FrontendView(TemplateView):
    def get_template_names(self, *args, **kwargs):
        # If no slug exists just serve the base so we can access the template switcher
        template_name = self.kwargs.get('slug', '_base')

        return ['frontend/{}.html'.format(template_name)]

semety/templates/clients/client_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete {{ tab.name }}</h1>
<form method="POST" action="">
    {% csrf_token %}
    <span class="error">Are you sure you want to delete?</span>

    <br><br>
    <input type="submit" class="button fill error" value="Confirm Delete" />
</form>
{% endblock content %}

semety/templates/clients/client_detail.html
{% extends 'base.html'%}
{% load thumbnail %}
{% block breadcrumb %}
<li><a href="{% url "clients:client_list" %}">Clients</a></li>
<li>{{ client.name }}</li>
{% endblock breadcrumb %}
{% block content %}
{% url "clients:client_update" pk=client.pk as client_update %}
{% url "clients:contact_add" client=client.pk as contact_add %}
{% include "clients/modals/client_form.html" with modalID="updatecontactModal" form=client_edit_form form_url=client_update %}
{% include "clients/modals/contact_form.html"  with modalID="addcontactModal" form=add_contact_form form_url=contact_add %}
<div class="grid-x grid-padding-x">
    <div class="large-9 cell">
        <h1>{{ client.name|title}}</h1>
    </div>
    <div class="large-3 cell text-right"><a data-open="updatecontactModal" class="button button-edit">  Edit Company</a></div>
    <div class="large-12 cell">
        <div class="tab-header form_item">
            <div class="grid-x">
                <div class="large-12 cell"><i class="fa fa-folder-open" aria-hidden="true"></i> Company Details</div>
            </div>
        </div>
    </div>
    <div class="large-12 cell">
        <div class="tab-content">
            <div class="grid-x grid-padding-x">
                <div class="large-2 cell">
					<div class="client_detail_logo">
						{% if client.logo %}
						{% thumbnail client.logo "200x100" as im %}
						<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
						{% endthumbnail %}
						{% else %}
						No logo
						<img src="/static/img/default.png" alt="" style="height:60px;">
						{% endif %}
					</div>
                </div>
                <div class="large-3 cell">
                    <h6>Name</h6>
                    <p>{{ client.name }}</p>
                    <h6>Full Address</h6>
                    <p>
                        {{ client.full_address|linebreaksbr }}
                    </p>
                </div>
                <div class="large-3 cell">
                    <h6>Main Phone</h6>
                    <p>{{ client.main_phone }}</p>
                    <h6>Main Email</h6>
                    <p>{{ client.main_email}}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="large-4 cell">
        <h1>Contacts</h1>
    </div>
    <div class="large-8 cell text-right">
        <a href="#" data-open="addcontactModal" class="button">Add Contact</a>
    </div>
    <div class="large-12 cell">
        <div class="tab-header form_item">
            <div class="grid-x">
                <div class="large-2 cell">Contact</div>
                <div class="large-4 cell">Email</div>
                <div class="large-3 cell">Phone</div>
                <div class="large-3 cell">Memos</div>
            </div>
        </div>
        <ul class="tab-section">
            {% for contact in client.contact_set.all %}
            <li>
                <a href="{% url "contacts:contact_detail" contact.client.pk contact.pk%}" class="tab-name grid-x">
                    <div class="large-2 cell">{{ contact.full_name }}</div>
                    <div class="large-4 cell">{{ contact.email }}</div>
                    <div class="large-3 cell">{{ contact.phone }}</div>
                    <div class="large-3 cell">{{ contact.memos.count }}</div>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

semety/templates/clients/client_list.html
{% extends 'base.html'%}
{% load thumbnail %}
{% block breadcrumb %}
<li>Clients</li>
{% endblock breadcrumb %}
{% block content %}
{% url "clients:client_add" as client_add %}
{% include "clients/modals/client_form.html" with modalID="addclientModal" form=client_add_form form_url=client_add %}
<div class="grid-x grid-padding-x">
        <div class="large-9 cell">
            <h1>Clients</h1>
        </div>
	<div class="large-3 cell text-right">
        <a data-open="addclientModal" class="button">Add client</a>
    </div>
	<div class="large-12 cell">
		<div class="tab-header form_item">
            <div class="grid-x">
			<div class="large-2 cell">Logo</div>
            <div class="large-4 cell"><a href="#"><i class="fa fa-sort faright" aria-hidden="true"></i> Client</a></div>
			<div class="large-3 cell">Full Address</div>
			<div class="large-3 cell">Main Phone Contact</div>
		</div>
        </div>
		<ul class="tab-section">
            {% if not client_list %}
                <li><p>No results found.</p></li>
            {% endif %}
			{% for client in client_list %}
			<li>
				<a href="/clients/{{ client.id }}" class="tab-name grid-x">
                    <div class="large-2 cell">
                    {% if client.logo %}
                        {% thumbnail client.logo "100x50" as im %}
                           <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                    {% else %}
                    No logo
                    <img src="/static/img/default.png" alt="" style="height:60px;">
                    {% endif %}
                    </div>
					<div class="large-4 cell clients_top_margin">{{ client.name }}</div>
					<div class="large-3 cell clients_top_margin">{{ client.full_address|linebreaksbr }}</div>
					<div class="large-3 cell clients_top_margin">{{ client.main_phone }}</div>
				</a>
				<div class="clearfix"></div>
			</li>
			{% endfor%}
		</ul>
    </div>
</div>

{% endblock %}

semety/templates/clients/contact_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete {{ tab.name }}</h1>
<form method="POST" action="">
    {% csrf_token %}
    <span class="error">Are you sure you want to delete?</span>

    <br><br>
    <input type="submit" class="button fill error" value="Confirm Delete" />
</form>
{% endblock content %}

semety/templates/clients/contact_detail.html
{% extends 'base.html'%}
{% load thumbnail %}
{% load humanize_custom %}
{% block breadcrumb %}
<li><a href="{% url "clients:client_list" %}">Clients</a></li>
<li><a href="{% url "clients:client_detail" contact.client.pk %}">{{ contact.client.name }}</a></li>
<li>{{ contact.full_name }}</li>
{% endblock breadcrumb %}
{% block content %}
{% url "clients:contact_update" client=contact.client.pk pk=contact.pk  as client_update%}
{% url "clients:contact_memo" client=contact.client.pk pk=contact.pk  as contact_memo %}
{% include "clients/modals/contact_form.html" with modalID="updatecontactModal" form=contact_edit_form form_url=client_update %}
{% include "clients/modals/contactmemo_form.html" with modalID="addMemoModal" semetyText="contact_memo" form=memo_form form_url=contact_memo %}
<!-- add contact form and contact form -->
<div class="grid-x grid-padding-x">
    <div class="large-9 cell">
        <h1>{{ contact.full_name|title}}</h1>
    </div>
    <div class="large-3 cell text-right">
        <a data-open="updatecontactModal" class="button button-edit">Edit Contact</a>

    </div>
    <div class="large-12 cell">
        <div class="tab-header form_item">
            <div class="grid-x">
                <div class="large-1 cell"><i class="fa fa-folder-open" aria-hidden="true"></i></div>
                <div class="large-11 cell"><a href="">Contact Details</a></div>
            </div>
        </div>
    </div>
    <div class="large-12 cell">
        <div class="tab-content">
            <br>
            <div class="large-3 cell">
				<div class="grid-x large-12 cell">
					<div class="large-4">
						<h6>Name</h6>
						<p>{{ contact.full_name }}</p>
					</div>
					<div class="large-4">
						<h6>Phone</h6>
						<p>{{ contact.phone }}</p>
					</div>
					<div class="large-4">
						<h6>Email</h6>
						<p>{{ contact.email}}</p>
					</div>
				</div>
            </div>
        </div>

		<div class="large-12 cell text-right">
			<a href="#" data-open="addMemoModal" class="button">Add Memo</a>
        </div>

        <div class="grid-x">
        <div class="large-12 cell">
        <div class="tab-header form_item">
			<div class="grid-x">
				<div class="large-4 cell">Name</div>
				<div class="large-6 cell">Description</div>
				<div class="large-2 cell">Date Added</div>
			</div>
        </div>
        <ul class="tab-section">
            {% if not contact.contactmemo_set.all %}
                <li class="text-center no-results">
                    No results found
                </li>
            {% endif %}
            {% for memo in contact.contactmemo_set.all %}
               {% include "clients/modals/contactmemo_form.html" with memo=memo semetyText=memo.revealSemetyText modalID=memo.modal form=memo.form form_url=memo.get_update_url %}
            {% endfor %}
            {% for memo in contact.contactmemo_set.all %}

            <li>
                <a data-open="{{ memo.modal }}" class="tab-name grid-x">
                    <div class="large-4 cell">{{ memo.title }}</div>
                    <div class="large-6 cell">{{ memo.plain_text|truncatechars:40 }}</div>
                    <div class="large-2 cell">{{ memo.datetime|naturaltime_recent_only }}</div>
                </a>
            </li>
            {% endfor %}
        </ul>
    <br/>
    </div>
</div>
{% endblock %}
{% block js %}
    <script src="/static/js/semety_text.js"></script>
    <script>
    semetyText("#contact_memo");
    {% for memo in contact.contactmemo_set.all %}
        semetyText("#{{ memo.revealSemetyText }}")
    {% endfor %}
    </script>
{% endblock js %}

semety/templates/clients/contact_form.html
{% extends 'base.html'%}
{% block content %}

<div class="large-9 cell">
<h1>Add Company</h1>
<form method="post" action="" enctype="multipart/form-data">
 {% csrf_token %}
	{{ form.as_p }}
	<input type="submit" name="" class="button" value="Save">

</form>
{% endblock %}

semety/templates/clients/contactmemo_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete {{ tab.name }}</h1>
<form method="POST" action="">
    {% csrf_token %}
    <span class="error">Are you sure you want to delete?</span>

    <br><br>
    <input type="submit" class="button fill error" value="Confirm Delete" />
</form>
{% endblock content %}

semety/templates/clients/contactmemo_form.html
{% extends 'base.html'%}
{% block content %}
<div class="grid-x">
<div class="large-6 cell">
<h1>Add Memo</h1>
<form method="post" action="" enctype="multipart/form-data">
 {% csrf_token %}
            <label for="">{{ form.title.label }}</label>
            <p>{{ form.title }}</p>
            <label for="">{{ form.text.label }}</label>
            {% include "workspace/includes/wysiwyg.html" with value=form.text.value semetyText="client_memo" %}
            <input type="submit" name="" class="button" value="Save">
</form>
</div>
</div>
{% endblock %}
{% block js %}
    <script src="/static/js/semety_text.js"></script>
    <script>
        semetyText("#client_memo");
    </script>
{% endblock js %}