semety/apps/api/urls.py
from rest_framework import routers
from django.conf.urls import url, include
from .serializers import ThreadList, TabList, InviteList

app_name = 'api'
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'tabs', TabList)
router.register(r'threads', ThreadList)
router.register(r'invites', InviteList)


urlpatterns = [
	url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

semety/apps/core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
import semety.apps.core.views as core_views

from .forms import LoginForm
from .views import *
app_name = "core"

urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'auth:login'}, name='logout'),


    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    path('activate/<str:uidb64>/<str:token>',core_views.activate, name='activate'),

]

semety/apps/network/urls.py
from .views import *
from django.conf.urls import url

app_name = "network"

urlpatterns = [
    url(r'^profile/$', UserProfile.as_view(), name="profile"),
    url(r'^profile/update/$', UserProfileUpdate.as_view(), name="profile_update"),
    url(r'^$', CompanyDetail.as_view(), name="company_detail"),
    url(r'^update/$', CompanyUpdate.as_view(), name="company_update"),
    url(r'^(?P<pk>\d+)/update/$', CompanyUserUpdate.as_view(), name="company_user_update"),
    url(r'^invite/$', CompanyInviteForm.as_view(), name="invite_create"),
    #url(r'^invite/(?P<pk>\d+)/$', CompanyInviteDetail.as_view(), name="invite_detail"),
    url(r'^invite/(?P<pk>\d+)/edit/$', CompanyInviteFormUpdate.as_view(), name="invite_edit"),
    url(r'^invite/(?P<pk>\d+)/delete/$', CompanyInviteFormDelete.as_view(), name="invite_delete"),
]

semety/apps/site/urls.py
from django.conf.urls import url

app_name = 'site'
urlpatterns = [
    #url(r'^$', UserProfileDetail.as_view(), name='home'),
]

semety/urls.py
""" URL config for semety project. """

from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.views import generic
from django.conf.urls.static import static
from .utils.views import FrontendView
from .apps.site.views import Homepage, WelcomePage, FeebackForm, About, Legal, Contact, Explore
from semety.apps.core.views import signup

admin.autodiscover()

from django.contrib.contenttypes.views import shortcut
from django.contrib.auth.views import password_change_done


urlpatterns = [

    # Admin URLs.
    path('admin/password_change/done/', password_change_done, name='password_change_done'),
    path('admin/', admin.site.urls),
    path('register/', signup, name="register"),
    path('', include('social.apps.django_app.urls', namespace='social')),
    path('', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('feedback/', FeebackForm.as_view(), name='login'),

    path('about/', About.as_view(), name='about'),
    path('legal/', Legal.as_view(), name='legal'),
    path('contact/', Contact.as_view(), name='contact'),
    path('explore/', Explore.as_view(), name='explore'),

    #Homepage
    path('', Homepage.as_view()),
    path('welcome/', WelcomePage.as_view()),
    path('', include('semety.apps.workspace.urls', namespace='workspace')),
    path('settings/', include('semety.apps.core.urls', namespace='core')),
    path('network/', include('semety.apps.network.urls', namespace='network')),
    path('api/', include('semety.apps.api.urls', namespace='workspace')),
    #path('network/', include('semety.apps.teams.urls', namespace='team')),
    path('clients/', include('semety.apps.clients.urls', namespace='clients')),
    path('notifications/', include('semety.apps.notifications.urls', namespace='notifications')),
    path('site/', include('semety.apps.site.urls', namespace='site')),
    #path('', include('semety.apps.teams.urls', namespace='teams')),


    # Permalink redirection service.
    path('<slug:content_type_id>-<slug:object_id>/', shortcut, name='permalink_redirect'),


    path('favicon.ico', generic.RedirectView.as_view(permanent=True)),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        path('404/', generic.TemplateView.as_view(template_name='404.html')),
        path('500/', generic.TemplateView.as_view(template_name='500.html')),
        path('frontend/', FrontendView.as_view()),
        path('frontend/<slug:slug>/', FrontendView.as_view())
    ]

semety/apps/core/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save

from .managers import UserManager
from sorl.thumbnail import ImageField


class UserPaymentModel(models.Model):

    stripe_id = models.CharField(
        max_length=400,
        blank=True,
    )

    # This is stored on the Stripe Card object as name.
    payer_name = models.CharField(
        max_length=100,
        blank=True,
        null=True,
    )

    # MMYYYY (or MYYYY)
    #
    # Month: payer_last_4[:-4]
    # Year: payer_last_4[-4:]

    payer_expiry = models.CharField(
        max_length=6,
        blank=True,
        null=True,
    )

    payer_last_4 = models.CharField(
        max_length=4,
        blank=True,
        null=True,
    )

    postal_address_line_1 = models.CharField(
        "address line 1",
        max_length=100,
        blank=True,
        null=True,
    )

    postal_address_line_2 = models.CharField(
        "address line 2",
        max_length=100,
        blank=True,
        null=True,
    )

    postal_address_city = models.CharField(
        "town / city",
        max_length=100,
        blank=True,
        null=True,
    )

    postal_address_postcode = models.CharField(
        "postcode",
        max_length=100,
        blank=True,
        null=True,
    )

    billing_address_same = models.BooleanField(
        default=True,
    )

    billing_address_line_1 = models.CharField(
        "address line 1",
        max_length=100,
        blank=True,
        null=True,
    )

    billing_address_line_2 = models.CharField(
        "address line 2",
        max_length=100,
        blank=True,
        null=True,
    )

    billing_address_city = models.CharField(
        "town / city",
        max_length=100,
        blank=True,
        null=True,
    )

    billing_address_postcode = models.CharField(
        "postcode",
        max_length=100,
        blank=True,
        null=True,
    )

    class Meta:
        abstract = True


class AddressAbstract(models.Model):

    address_line_1 = models.CharField(
        max_length=200,
        null=True,
    )

    city = models.CharField(
        max_length=200,
        null=True,
    )

    county = models.CharField(
        max_length=200,
        null=True,
    )

    postal_code = models.CharField(
        max_length=200,
        null=True,
    )

    country = models.CharField(
        max_length=200,
        null=True,
    )

    class Meta:
        abstract = True


class Company(AddressAbstract, UserPaymentModel):

    name = models.CharField(
        max_length=200,
    )

    logo = ImageField(
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(
        _('email address'),
        unique=True
    )

    profile_picture = ImageField(
        null=True,
        blank=True,
    )

    first_name = models.CharField(
        _('first name'),
        max_length=30,
        blank=True
    )

    last_name = models.CharField(
        _('last name'),
        max_length=30,
        blank=True
    )

    date_joined = models.DateTimeField(
        _('date joined'),
        auto_now_add=True
    )

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    email_confirmed = models.BooleanField(
        default=False,
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject=subject, html_message=message, message=message, from_email="noreply@semety.com", recipient_list=[self.email], **kwargs)


    def __str__(self):
        return self.get_full_name()

    @property
    def company(self):
        try:
            return self.companyuser.company
        except:
            return None

    @property
    def tabs(self):
        return self.companyuser.access.all()

    @property
    def threads(self):
        for tab in self.companyuser.access.all():
            for thread in tab.thread_set.all():
                yield thread


    @property
    def notifications(self):
        from ..notifications.models import Notification
        return Notification.objects.filter(user=self)

    @property
    def unread_notifications(self):
        return self.notifications.filter(read=False)

    @property
    def status(self):
        from ..workspace.models import Status
        return Status.objects.all()

@receiver(post_save, sender=User)
def create_company_user(sender, instance, created, **kwargs):
    if created:
        company = Company.objects.create(name="Company Name")
        CompanyUser.objects.create(
            user=instance,
            company=company,
            admin=True,
        )


class CompanyUser(models.Model):

    company = models.ForeignKey(
        Company,
        on_delete=models.PROTECT
    )

    user = models.OneToOneField(
        User,
        on_delete=models.PROTECT
    )

    job_title = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    admin = models.BooleanField(
        default=False,
    )

    access = models.ManyToManyField(
        'workspace.Tab',
    )

    @models.permalink
    def get_update_url(self):
        return ("network:company_user_update", (), {
            "pk": self.pk,
        })

    @property
    def reveal(self):
        return "reveal_modal_companyuser" + str(self.pk)

    @property
    def form(self):
        from .forms import CompanyUserForm
        return CompanyUserForm(instance=self, user=self.user)


class Invite(models.Model):

    invite_from = models.ForeignKey(
        User,
        on_delete=models.PROTECT
    )

    invite_to = models.EmailField(
        max_length=400,
        null=True,
    )

    company = models.ForeignKey(
        Company,
        on_delete=models.PROTECT,
        null=True
    )

    code = models.CharField(
        max_length=400,
        null=True,
        blank=True,
    )

    datetime = models.DateTimeField(
        auto_now_add=True
    )

    def get_absolute_url(self):
        return reverse('network:invite_detail', kwargs={'pk': self.pk})

semety/apps/site/forms.py
from django import forms
from .models import User

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("first_name", "last_name", "profile_picture")

semety/apps/api/views.py
from django.shortcuts import render

# Create your views here.

semety/apps/clients/views.py
from .models import Client, Contact, ContactMemo
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView
from django.views.generic.edit import ModelFormMixin
from .forms import ClientForm, ContactForm, ContactMemoForm
from django.urls import reverse





def GetUser(teammate):
    return teammate.user

class ClientList(ListView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_add_form'] = ClientForm
        return context

    def get_queryset(self):
        return Client.objects.filter(team=self.request.user.company)


class ClientDetail(DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_edit_form'] = ClientForm(instance=self.object)
        context['add_contact_form'] = ContactForm
        return context


class ClientCreate(CreateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        Form = form.save(commit=False)
        Form.user = self.request.user
        Form.team = self.request.user.company
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class ClientUpdate(UpdateView):
    model = Client
    form_class = ClientForm


class ClientDelete(DeleteView):
    model = Client

    def get_success_url(self):
        return reverse('clients:client_list', kwargs={})


#Contacts

class ContactDetail(DetailView):
    model = Contact

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['memo_form'] = ContactMemoForm
        context['contact_edit_form'] = ContactForm(instance=self.object)
        return context


class ContactDelete(DeleteView):
    model = Contact

    def get_success_url(self):
        return reverse('clients:client_detail', kwargs={'pk': self.kwargs['client']})


class ContactMemoUpdate(UpdateView):
    model = ContactMemo
    form_class = ContactMemoForm


class ContactMemoDelete(DeleteView):
    model = ContactMemo

    def get_success_url(self):
        return reverse('clients:contact_detail', kwargs={'client': self.kwargs['client'], 'pk': self.kwargs['contact']})


class ContactMemo(CreateView):
    model = ContactMemo
    form_class = ContactMemoForm

    def form_valid(self, form):
        Form = form.save(commit=False)
        Form.contact = Contact.objects.get(pk=self.kwargs['pk'])
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class ContactCreate(CreateView):
    model = Contact
    form_class = ContactForm

    def form_valid(self, form):
        Form = form.save(commit=False)
        Form.client = Client.objects.get(pk=self.kwargs['client'])
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class ContactUpdate(UpdateView):
    model = Contact
    form_class = ContactForm

semety/apps/core/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.views.generic import DetailView, UpdateView
from django.conf import settings
from .forms import SignUpForm
from .tokens import account_activation_token

User = get_user_model()


@login_required
def home(request):
    return render(request, 'core/home.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('core/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)

            return redirect('core:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'registration/register.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'core/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()
        login(request, user, backend=settings.AUTHENTICATION_BACKENDS[2])
        return redirect('workspace:tab_list')
    else:
        return render(request, 'core/account_activation_invalid.html')

semety/templates/core/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'core:activate' uidb64=uid token=token %}
{% endautoescape %}

semety/templates/core/company_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load humanize %}
{% block breadcrumb %}

{% endblock breadcrumb %}
{% block content %}
 <div class="grid-x grid-padding-x">
        <div class="large-12 cell">
                            <div class="grid-x">
                <div class="large-12 cell">
            <h1>Network</h1>
            </div>
        </div>
            <div class="tab-header form_item">
                <div class="grid-x">
                    <div class="large-4 cell">Full Name</div>
                    <div class="large-4 cell">Email</div>
                    <div class="large-2 cell">Admin</div>
                    <div class="large-2 cell">Access</div>
                </div>
            </div>
            <div class="tab-section">
                {% for companyuser in company.companyuser_set.all %}
                <li>
                    <a data-open="{{ companyuser.reveal }}" class="tab-name grid-x">
                        <div class="large-4 cell"> {{ companyuser.user.get_full_name }}</div>
                        <div class="large-4 cell">{{ companyuser.user.email }}</div>
                        <div class="large-2 cell">{{ companyuser.admin }}</div>
                        <div class="large-2 cell">View</div>
                    </a>
                </li>
                {% endfor %}
            </div>
        </div>

            <div class="large-12 cell">
                            <br>
                <div class="grid-x">
                <div class="large-8 cell">
                    <h1>Pending Invites</h1>
                </div>
                <div class="large-4 cell text-right">
                    <a href="#" class="button fill">Invite User</a>
                </div>
            </div>
            <div class="tab-header form_item">
                <div class="grid-x">
                    <div class="large-8 cell">Invite To</div>
                    <div class="large-2 cell">Status</div>
                     <div class="large-2 cell">Date Invited</div>
                </div>
            </div>
            <div class="tab-section">
                {% if not company.invite_set.all %}
               <li>
                    <div class="large-12 cell text-center no-results">No invites pending.</div>
                </li>
                {% endif %}
                {% for invite in company.invite_set.all %}
                <div class="large-12 cell task">
                    <a href="" class="grid-x black">
                        <div class="large-8 cell"> {{ invite.invite_to }}</div>
                        <div class="large-2 cell">Pending</div>
                        <div class="large-2 cell">{{ invite.datetime|naturaltime }}</div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% for companyuser in company.companyuser_set.all %}
    {% include "core/modals/companyuser_form.html" with modalID=companyuser.reveal form=companyuser.form form_url=companyuser.get_update_url companyuser=companyuser %}
{% endfor %}
{% endblock content %}

semety/templates/core/user_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block breadcrumb %}
    <li>Profile</li>
{% endblock breadcrumb %}
{% block content %}
{% url "network:profile_update" as form_url %}

{% include "site/includes/profile_form.html" with modalID="editProfileModal" form=form form_url=form_url %}
<div class="grid-x grid-padding-x">
<div class="large-9 cell">
		<h1>Profile Settings</h1>
	</div>
		<div class="large-3 cell text-right"><a data-open="editProfileModal" class="button button-edit">Edit Profile</a></div>

		<div class="large-12 cell">
		<div class="tab-header form_item">
            <div class="grid-x">
			<div class="large-12 cell">
				<i class="fa fas fa-cog"></i> Profile settings
			</div>
        </div>
		</div>
		<div class="tab-content nopad">
		<div class="settings">
            <div class="grid-x">
			<div class="large-3 cell">
				<center><br/>
					{% csrf_token %}

                    {% if user.profile_picture %}
                        {% thumbnail user.profile_picture "200x200" crop="center" as im %}
                           <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="profile_picture">
                        {% endthumbnail %}
                    {% else %}
                    <img src="/static/img/default.png" class="no-logo" alt="no logo">
					<p>You have no logo</p>
                    {% endif %}
				</center>
			</div>
			<div class="large-5 cell"><br/><br/>
				<div class="profilesettings">
					<div class="large-12 cell">
						<div class="large-12 cell">
							<h5>Your information</h5>
						</div>
						<div class="grid-x">
							<div class="large-6 cell">
								Full Name:
							</div>
							<div class="large-6 cell">
								{{ user.get_full_name|title }}
							</div>
                            <div class="large-6 cell">
                                Email
                            </div>
                            <div class="large-6 cell">
                                {{ user.email }}
                            </div>
							<div class="large-6 cell">
								Password:
							</div>
							<div class="large-6 cell">
								<a href="#">Change password</a>
							</div>
							<div class="large-6 cell">
								Subscription:
							</div>
							<div class="large-6 cell">
								BETA (<a href="#">change</a>)
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="large-4 cell"><br/><br/>
				<div class="large-12 cell"><br/>
					<h5>Discover more</h5>
					<a href="#">F.A.Q. About using Semety</a><br/>
					<a href="#">How does my subscription work?</a><br/>
					<a href="#">Semety network tutorial</a><br/>
					<a href="#">Terms and conditions</a><br/>
				</div>
			</div>
		</div>
		</div>
	</div>
</form>
{% endblock%}