semety/apps/api/urls.py
from rest_framework import routers
from django.conf.urls import url, include
from .serializers import ThreadList, TabList, InviteList

app_name = 'api'
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'tabs', TabList)
router.register(r'threads', ThreadList)
router.register(r'invites', InviteList)


urlpatterns = [
	url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

semety/apps/core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
import semety.apps.core.views as core_views

from .forms import LoginForm
from .views import *
app_name = "core"

urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'auth:login'}, name='logout'),


    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    path('activate/<str:uidb64>/<str:token>',core_views.activate, name='activate'),

]

semety/apps/site/urls.py
from django.conf.urls import url

app_name = 'site'
urlpatterns = [
    #url(r'^$', UserProfileDetail.as_view(), name='home'),
]

semety/apps/workspace/urls.py
from django.urls import path
from .views import *

app_name = 'workspace'

urlpatterns = [
    path('workspace/', TabList.as_view(), name='tab_list'),

    path('workspace/manage/', TabManage.as_view(), name='tab_manage'),
    path('workspace/manage/create/', TabCreate.as_view(), name='tab_create'),
    path('workspace/manage/<slug:slug>/update/', TabUpdate.as_view(), name='tab_update'),
    path('workspace/manage/<slug:slug>/delete/', TabDelete.as_view(), name='tab_delete'),


    path('workspace/<slug:slug>/thread/', RedirectTab.as_view(), name="original_view"),
    path('workspace/<slug:slug>/', TabDetail.as_view(), name='tab_detail'),

    path('workspace/<slug:tab>/thread/<slug:slug>/', ThreadDetail.as_view(), name='thread_detail'),
    path('workspace/<slug:tab>/thread/<slug:slug>/edit/', ThreadEdit.as_view(), name='thread_update'),
    path('workspace/<slug:tab>/thread/<slug:slug>/edit_message/', ThreadEditMessage.as_view(), name='thread_update_message'),
    path('workspace/<slug:tab>/thread/<slug:slug>/delete/', ThreadDelete.as_view(), name='thread_delete'),
    path('workspace/<slug:tab>/add-thread/', ThreadCreate.as_view(), name='thread_create'),

    path('workspace/<slug:tab>/thread/<slug:thread>/reply/', ReplyCreate.as_view(), name='thread_reply'),
    path('workspace/<slug:tab>/thread/<slug:thread>/reply/<int:pk>/edit/', ReplyEdit.as_view(), name='reply_update'),
    path('workspace/<slug:tab>/thread/<slug:thread>/reply/<int:pk>/delete/', ReplyDelete.as_view(), name='reply_delete'),

]

semety/urls.py
""" URL config for semety project. """

from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.views import generic
from django.conf.urls.static import static
from .utils.views import FrontendView
from .apps.site.views import Homepage, WelcomePage, FeebackForm, About, Legal, Contact, Explore
from semety.apps.core.views import signup

admin.autodiscover()

from django.contrib.contenttypes.views import shortcut
from django.contrib.auth.views import password_change_done


urlpatterns = [

    # Admin URLs.
    path('admin/password_change/done/', password_change_done, name='password_change_done'),
    path('admin/', admin.site.urls),
    path('register/', signup, name="register"),
    path('', include('social.apps.django_app.urls', namespace='social')),
    path('', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('feedback/', FeebackForm.as_view(), name='login'),

    path('about/', About.as_view(), name='about'),
    path('legal/', Legal.as_view(), name='legal'),
    path('contact/', Contact.as_view(), name='contact'),
    path('explore/', Explore.as_view(), name='explore'),

    #Homepage
    path('', Homepage.as_view()),
    path('welcome/', WelcomePage.as_view()),
    path('', include('semety.apps.workspace.urls', namespace='workspace')),
    path('settings/', include('semety.apps.core.urls', namespace='core')),
    path('network/', include('semety.apps.network.urls', namespace='network')),
    path('api/', include('semety.apps.api.urls', namespace='workspace')),
    #path('network/', include('semety.apps.teams.urls', namespace='team')),
    path('clients/', include('semety.apps.clients.urls', namespace='clients')),
    path('notifications/', include('semety.apps.notifications.urls', namespace='notifications')),
    path('site/', include('semety.apps.site.urls', namespace='site')),
    #path('', include('semety.apps.teams.urls', namespace='teams')),


    # Permalink redirection service.
    path('<slug:content_type_id>-<slug:object_id>/', shortcut, name='permalink_redirect'),


    path('favicon.ico', generic.RedirectView.as_view(permanent=True)),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        path('404/', generic.TemplateView.as_view(template_name='404.html')),
        path('500/', generic.TemplateView.as_view(template_name='500.html')),
        path('frontend/', FrontendView.as_view()),
        path('frontend/<slug:slug>/', FrontendView.as_view())
    ]

semety/apps/api/models.py
from django.db import models

# Create your models here.

semety/apps/clients/models.py
from django.db import models
from semety.apps.core.models import Company
from sorl.thumbnail import ImageField



class AddressAbstract(models.Model):

    address_line_1 = models.CharField(
        max_length=200,
        null=True,
    )

    city = models.CharField(
        max_length=200,
        null=True,
    )

    county = models.CharField(
        max_length=200,
        null=True,
    )

    postal_code = models.CharField(
        max_length=200,
        null=True,
    )

    country = models.CharField(
        max_length=200,
        null=True,
    )


    def full_address(self):
        return self.address_line_1 + '\n' + self.city + '\n' + self.county + '\n' + self.postal_code + '\n' + self.country


    class Meta:
        abstract =True


class Client(AddressAbstract):

    name = models.CharField(
        max_length=200,
    )

    main_phone = models.CharField(
        max_length=200,
    )

    main_email = models.EmailField(
        max_length=200,
    )

    logo = ImageField(
        null=True,
        blank=True,
    )

    team = models.ForeignKey(
        Company,
        on_delete=models.PROTECT,
    )

    class Meta:
        ordering = ['name']

    @models.permalink
    def get_absolute_url(self):
            return ("clients:client_detail", (), {
                "pk": self.pk
            })


    @models.permalink
    def get_delete_url(self):
            return ("clients:client_delete", (), {
                "pk": self.pk,
            })


class Contact(models.Model):

    client = models.ForeignKey(
        Client,
        blank=True,
        on_delete=models.CASCADE,
    )

    full_name = models.CharField(
        max_length=200,
        null=True,
        )


    email = models.EmailField(
        max_length=400,
    )

    phone = models.CharField(
        max_length=300,
    )

    memo = models.TextField(
        null=True,
    )

    @property
    def memos(self):
        return self.contactmemo_set.all()


    @models.permalink
    def get_delete_url(self):
            return ("clients:contact_delete", (), {
                "client": self.client.pk,
                "pk": self.pk,
            })

    @models.permalink
    def get_absolute_url(self):
            return ("clients:contact_detail", (), {
                "client": self.client.pk,
                "pk": self.pk,
            })


class ContactMemo(models.Model):

    contact = models.ForeignKey(
        Contact,
        on_delete=models.CASCADE,
    )

    title = models.CharField(
        max_length=200,
        null=True,
    )

    text = models.TextField(
        null=True,
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
        null=True
    )

    @models.permalink
    def get_absolute_url(self):
            return ("clients:contact_detail", (), {
                "client": self.contact.client.pk,
                "pk": self.contact.pk,
            })


    @models.permalink
    def get_update_url(self):
            return ("clients:contact_memo_update", (), {
                "client": self.contact.client.pk,
                "contact": self.contact.pk,
                "pk": self.pk,
            })

    @models.permalink
    def get_delete_url(self):
            return ("clients:contact_memo_delete", (), {
                "client": self.contact.client.pk,
                "contact": self.contact.pk,
                "pk": self.pk,
            })

    @property
    def modal(self):
        return "memo_modal_" + str(self.pk)

    @property
    def plain_text(self):
        text = self.text
        tags_allowed = ["<h1>", "</h1>", "<h2>", "</h2>", "<h3>", "</h3>", "<h4>", "<h5>", "<h6>", "</h6>", "<div>", "</div>", "<br>", "<b>", "</b>", "<i>", "</i>", "<u>", "</u>"]
        for x in tags_allowed:
            text = text.replace(x, "")
        return text

    @property
    def revealSemetyText(self):
        return "revealSemetyText_memo_" + str(self.pk)

    @property
    def form(self):
        from .forms import ContactMemoForm
        return ContactMemoForm(instance=self)

semety/apps/workspace/models.py
from django.db import models
from django.contrib.auth import get_user_model
from semety.apps.core.models import Company
from django.template.defaultfilters import slugify
from .slug_helpers import unique_slugify
from django.dispatch import receiver
from django.db.models.signals import post_save


User = get_user_model()

class Status(models.Model):

    name = models.CharField(
        max_length=200,
    )

    color = models.CharField(
        max_length=200,
        null=True,
    )

    team = models.ForeignKey(
        Company,
        null=True,
        on_delete=models.PROTECT,
    )

    def __str__(self):
        return self.name

    @property
    def css_class(self):
        return "builtin-status-" + slugify(self.name)

    @property
    def css_class_border(self):
        return self.css_class + "-border"

    @property
    def css_class_background(self):
        return self.css_class + "-background"

    @property
    def css_class_color(self):
        return self.css_class + "-color"


class Tab(models.Model):

    name = models.CharField(
        max_length=200,
    )

    icon = models.CharField(
        max_length=200,
        blank=True
        )

    team = models.ForeignKey(
        Company,
        null=True,
        on_delete=models.PROTECT,
    )

    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
    )

    datetime_created = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True,
    )

    slug = models.SlugField()

    def save(self, **kwargs):
        unique_slugify(self, self.name)
        super().save(**kwargs)
        self.created_by.companyuser.access.add(self)

    @models.permalink
    def get_absolute_url(self):
            return ("workspace:tab_detail", (), {
                "slug": self.slug
            })

    def __str__(self):
        return self.name

    def last_activity(self):
        threads = Thread.objects.filter(tab=self)

        if threads:
            thread = threads.latest("datetime")
            replies =  Reply.objects.filter(thread__in=threads)
            if replies:
                reply = replies.latest("datetime")
                if thread.datetime > reply.datetime:
                    return thread
                else:
                    return reply
            else:
                return thread
        else:
            return None

    @models.permalink
    def get_update_url(self):
        return ("workspace:tab_update", (), {
            "slug": self.slug,
        })

    @property
    def reveal(self):
        return "reveal_modal_tab" + str(self.pk)

    @property
    def form(self):
        from .forms import TabForm
        return TabForm(instance=self)


class Thread(models.Model):

    tab = models.ForeignKey(
        Tab,
        on_delete=models.CASCADE,
        )

    user = models.ForeignKey(
        User,
        related_name="created_by",
        on_delete=models.PROTECT,
    )

    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
    )

    title = models.CharField(
        max_length=200,
        null=True,
    )

    text = models.TextField(
        null=True,
    )

    assigned = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.PROTECT,
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
        null=True
        )

    last_updated = models.DateTimeField(
        null=True,
        auto_now=True,
    )

    slug = models.SlugField()

    @models.permalink
    def message_update_url(self):
        return ("workspace:thread_update_message", (), {
            "tab": self.tab.slug,
            "slug": self.slug
        })

    @models.permalink
    def get_absolute_url(self):
            return ("workspace:thread_detail", (), {
                "tab": self.tab.slug,
                "slug": self.slug
            })

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return str(self.tab) + ' - ' + str(self.title)

    @property
    def reveal(self):
        return "reveal_modal_thread" + str(self.pk)

    @property
    def revealSemetyText(self):
        return "reveal_modal_thread_semety" + str(self.pk)

    @property
    def form(self):
        from .forms import ThreadMessageForm
        return ThreadMessageForm(instance=self)

    def replies(self):
        return Reply.objects.filter(thread=self)

    def save(self, changed_last_update=False, **kwargs):
        if changed_last_update:
            self.changed_last_update = True
        else:
            self.changed_last_update = False
            unique_slugify(self, self.title)
        super().save(**kwargs)

    @property
    def files(self):
        return self.threadfile_set.all()

class Reply(models.Model):

    thread = models.ForeignKey(
        Thread,
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
    )

    text = models.TextField(
        null=True,
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
        null=True
    )

    @property
    def form(self):
        from .forms import ReplyForm
        return ReplyForm(instance=self)

    @models.permalink
    def message_update_url(self):
        return ("workspace:reply_update", (), {
            "tab": self.thread.tab.slug,
            "thread": self.thread.slug,
            "pk": self.pk,

        })

    @property
    def revealSemetyText(self):
        return "reveal_modal_reply_semety" + str(self.pk)

    @property
    def reveal(self):
        return "reveal_modal_reply" + str(self.pk)

    @models.permalink
    def get_absolute_url(self):
            return ("workspace:thread_detail", (), {
                "tab": self.thread.tab.slug,
                "slug": self.thread.slug
            })

    @models.permalink
    def get_delete_url(self):
            return ("workspace:reply_delete", (), {
                "tab": self.thread.tab.slug,
                "thread": self.thread.slug,
                "pk": self.pk,
            })

    def save(self, **kwargs):
        super().save(**kwargs)
        self.thread.last_updated = self.datetime
        self.thread.save(changed_last_update=True)


class ThreadFile(models.Model):

    thread = models.ForeignKey(
        Thread,
        on_delete=models.CASCADE,
    )

    file = models.FileField(
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
    )

@receiver(post_save, sender=Thread)
def thread_notification(sender, instance, created, **kwargs):
        from ..notifications.helpers import notify
        if not instance.changed_last_update:
            notify(user=instance.assigned, created=created, model="workspace_thread", model_instance=instance)


@receiver(post_save, sender=Reply)
def reply_notification(sender, instance, created, **kwargs):
        from ..notifications.helpers import notify
        notify(user=instance.thread.user, created=created, model="workspace_reply", model_instance=instance)
        notify(user=instance.thread.assigned, created=created, model="workspace_reply", model_instance=instance)

semety/apps/api/views.py
from django.shortcuts import render

# Create your views here.

semety/apps/notifications/views.py
from django.views.generic import ListView
from .models import Notification
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect

class NotificationList(ListView):
    model = Notification


def NotificationRead(request, pk):
    notification = get_object_or_404(
        Notification, user=request.user, id=pk)
    notification.read = True
    notification.save(send_email=False)

    return redirect(notification.model_instance.get_absolute_url())


def NotifcationMarkAllAsRead(request):
    for notifcation in Notification.objects.filter(user=request.user):
        notifcation.read = True
        notifcation.save(send_email=False)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

semety/templates/workspace/modals/reply_form.html
<div class="reveal" id="{{ modalID }}" data-reveal>
    <div class="moduleform">
        <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Message</h1>
        <form action="{{ form_url }}" method="post">
        {% for field in form %}
            {% if field.name == "text" %}
                <label for="">{{ field.label }}</label>
                {% include "workspace/includes/wysiwyg.html" with value=field.value semetyText=semetyText %}
            {% endif %}

        {% endfor %}
        {% csrf_token %}
        <input class="buttoncustom" type="submit" value="Save">
        {% if reply.get_delete_url %}
            <a class="button button-edit float-right" href="{{ reply.get_delete_url }}"><i class="fa fa-trash" aria-hidden="true"></i> Delete Message</a>
        {% endif %}
       </form>
         <button class="close-button" data-close aria-label="Close modal" type="button">
            <span aria-hidden="true">&times;</span>
          </button>

    </div>
</div>

semety/templates/workspace/modals/tab_form.html
<div class="reveal" id="{{ modalID }}" data-reveal>
    <div class="moduleform">
        <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Tab </h1>
        <form action="{{ form_url }}" id="tabform" method="post">
                {% csrf_token %}
                {{ form.name.label_tag }}
                <p>{{ form.name }}</p>

                {{ form.icon.label_tag }}
                <h1 id="icon_display"><i class=""></i></h1>
                <p>{{ form.icon }}</p>

                 <input class="buttoncustom" id="addtab" type="submit" value="Save" name="">

            {% if form.instance.pk %}
			<a class="button button-edit float-right" href="{% url "workspace:tab_delete" tab.slug %}"><i class="fa fa-trash" aria-hidden="true"></i> Delete tab</a>
            {% endif %}

        </form>
         <button class="close-button" data-close aria-label="Close modal" type="button">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>
</div>

semety/templates/workspace/modals/thread_edit.html
<!-- probably not needed if create a "thread_form" and pass it an instance {{ form.as_p }} ect.. -->
<div class="reveal" id="threadeditModal" data-reveal>
    <h3 class="modalintro">Edit: {{ thread.title }}</h3>
    <form action="thread/add/" id="threadform" method="post">
         {% csrf_token %}
    <p><label for="id_status">Assign the thread status:</label>
    <fieldset class="radio-buttons">

    <input type="radio" value="1" name="status" class="radio" id="radio1">
    <label for="radio1">Active</label>

    <input type="radio" value="2" name="status" class="radio" id="radio2">
    <label for="radio2" class="pendingrad">Pending</label>

    <input type="radio" value="3" name="status" class="radio closedrad" id="radio3">
    <label for="radio3">Closed</label>

    </fieldset><br/>
    <p><label for="id_title">Choose a title:</label> <input id="id_title" maxlength="200" name="title" type="text" placeholder="..." required /></p>
    <p><label for="id_text">Your text:</label><textarea class="wysiwyg" id="textarea-edit" cols="40" id="id_text" name="text" rows="10" placeholder="..."></textarea></p>
    <p><label for="id_assigned"><b class="left">Assigned members:<b class="right"><a href="/network/" target="_blank">Invite members?</a></label>
     <select id="id_assigned" name="assigned">
    <option value="" selected="selected">---------</option>
    {% for person in thread.members %}
        <option value="{{ person.user.id }}">{{ person.user.username }}</option>
    {% endfor %}
    </select></p></p>
    <div class="left">
        <a class="buttoncustom" onclick="saveThread()">Save</a>
    </div>
    <div class="right">
    <a class="buttoncustom greybg" onclick="deleteThread()"><i class="fa fa-trash" aria-hidden="true"></i> Delete thread</a>
    </div>
    </form>
     <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
      </button>
</div>

semety/templates/workspace/modals/thread_form.html
<style>

{% for status in request.user.status %}
    .radio-buttons input[type="radio"]:checked+label.status{{ status.pk }}:before {
        content: '\2714';
        text-indent: .9em;
        color: #FFF !important;
        background-color: {{ status.color }} !important;
    }
{% endfor %}

</style>
<div class="reveal" id="{{ modalID }}" data-reveal>
    <div class="moduleform">
        <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Thread</h1>
        <form action="{{ form_url }}" method="post">

        {% for field in form %}

        {% if field.name == "text" %}
            <label for="">{{ field.label }}</label>
            {% include "workspace/includes/wysiwyg.html" with value=field.value semetyText="threadbox" %}
        {% elif field.name == "status" %}
            <label for="">{{ field.label }}</label>
            <fieldset class="radio-buttons">
                {% for choice in form.status.field.choices %}
                        <input type="radio" name="status" id="status{{choice.0}}" value="{{choice.0}}"
                          {% ifequal  field.value choice.0 %}
                             checked="checked"
                          {% endifequal %}/>
                        <label class="status{{choice.0}}" for="status{{ choice.0 }}">{{choice.1}}</label>

                {% endfor %}
            </fieldset>
            <p></p>
        {% else %}
        <p>
            <label for="">{{ field.label }}</label>
            {{ field }}
        </p>
        {% endif %}

        {% endfor %}
        {% csrf_token %}
        <input class="buttoncustom" type="submit" value="Save">
        {% if form.instance.pk %}
            <a class="button button-edit float-right" href="{{ form_delete_url }}"><i class="fa fa-trash" aria-hidden="true"></i> Delete Message</a>
        {% endif %}
        </form>
         <button class="close-button" data-close aria-label="Close modal" type="button">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>
</div>