semety/apps/api/urls.py
from rest_framework import routers
from django.conf.urls import url, include
from .serializers import ThreadList, TabList, InviteList

app_name = 'api'
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'tabs', TabList)
router.register(r'threads', ThreadList)
router.register(r'invites', InviteList)


urlpatterns = [
	url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

semety/apps/core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
import semety.apps.core.views as core_views

from .forms import LoginForm
from .views import *
app_name = "core"

urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'auth:login'}, name='logout'),


    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    path('activate/<str:uidb64>/<str:token>',core_views.activate, name='activate'),

]

semety/apps/site/urls.py
from django.conf.urls import url

app_name = 'site'
urlpatterns = [
    #url(r'^$', UserProfileDetail.as_view(), name='home'),
]

semety/urls.py
""" URL config for semety project. """

from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.views import generic
from django.conf.urls.static import static
from .utils.views import FrontendView
from .apps.site.views import Homepage, WelcomePage, FeebackForm, About, Legal, Contact, Explore
from semety.apps.core.views import signup

admin.autodiscover()

from django.contrib.contenttypes.views import shortcut
from django.contrib.auth.views import password_change_done


urlpatterns = [

    # Admin URLs.
    path('admin/password_change/done/', password_change_done, name='password_change_done'),
    path('admin/', admin.site.urls),
    path('register/', signup, name="register"),
    path('', include('social.apps.django_app.urls', namespace='social')),
    path('', include(('django.contrib.auth.urls', 'auth'), namespace='auth')),
    path('feedback/', FeebackForm.as_view(), name='login'),

    path('about/', About.as_view(), name='about'),
    path('legal/', Legal.as_view(), name='legal'),
    path('contact/', Contact.as_view(), name='contact'),
    path('explore/', Explore.as_view(), name='explore'),

    #Homepage
    path('', Homepage.as_view()),
    path('welcome/', WelcomePage.as_view()),
    path('', include('semety.apps.workspace.urls', namespace='workspace')),
    path('settings/', include('semety.apps.core.urls', namespace='core')),
    path('network/', include('semety.apps.network.urls', namespace='network')),
    path('api/', include('semety.apps.api.urls', namespace='workspace')),
    #path('network/', include('semety.apps.teams.urls', namespace='team')),
    path('clients/', include('semety.apps.clients.urls', namespace='clients')),
    path('notifications/', include('semety.apps.notifications.urls', namespace='notifications')),
    path('site/', include('semety.apps.site.urls', namespace='site')),
    #path('', include('semety.apps.teams.urls', namespace='teams')),


    # Permalink redirection service.
    path('<slug:content_type_id>-<slug:object_id>/', shortcut, name='permalink_redirect'),


    path('favicon.ico', generic.RedirectView.as_view(permanent=True)),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        path('404/', generic.TemplateView.as_view(template_name='404.html')),
        path('500/', generic.TemplateView.as_view(template_name='500.html')),
        path('frontend/', FrontendView.as_view()),
        path('frontend/<slug:slug>/', FrontendView.as_view())
    ]

semety/apps/notifications/models.py
from django.db import models
from ..workspace.models import Thread, Reply
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.urls import reverse

User = get_user_model()

MODEL_TYPES = (
    ('workspace_thread', 'Thread'),
    ('workspace_reply', 'Reply'),
)

class ModalsTypes(models.Model):

    workspace_thread = models.ForeignKey(
        Thread,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    workspace_reply = models.ForeignKey(
        Reply,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    class Meta:
        abstract = True,


class Notification(ModalsTypes):

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    text = models.TextField(
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
    )

    read = models.BooleanField(
        default=False,
    )

    model = models.CharField(
        choices=MODEL_TYPES,
        max_length=200,
    )

    icon = models.CharField(
        max_length=200,
        null=True,
    )


    @models.permalink
    def get_absolute_url(self):
        return ("notifications:notification_view", {
            self.pk,
        })


    class Meta:
        ordering = ('-datetime',)

    @property
    def model_instance(self):
        if self.model == "workspace_thread":
            return self.workspace_thread
        elif self.model == "workspace_reply":
            return self.workspace_reply

    def __str__(self):
        return self.text

    def save(self, send_email=True, **kwargs):
        super().save(**kwargs)
        if send_email:
            current_site = "http://localhost:8000" #get_current_site(self.request)
            subject = 'New Notification from Semety'
            message = render_to_string('email/notification.html', {
                'user': self.user,
                'notification': self,
                'domain': current_site, #.domain,
                #'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                #'token': account_activation_token.make_token(user),
            })
            self.user.email_user(subject, message)

semety/apps/workspace/models.py
from django.db import models
from django.contrib.auth import get_user_model
from semety.apps.core.models import Company
from django.template.defaultfilters import slugify
from .slug_helpers import unique_slugify
from django.dispatch import receiver
from django.db.models.signals import post_save


User = get_user_model()

class Status(models.Model):

    name = models.CharField(
        max_length=200,
    )

    color = models.CharField(
        max_length=200,
        null=True,
    )

    team = models.ForeignKey(
        Company,
        null=True,
        on_delete=models.PROTECT,
    )

    def __str__(self):
        return self.name

    @property
    def css_class(self):
        return "builtin-status-" + slugify(self.name)

    @property
    def css_class_border(self):
        return self.css_class + "-border"

    @property
    def css_class_background(self):
        return self.css_class + "-background"

    @property
    def css_class_color(self):
        return self.css_class + "-color"


class Tab(models.Model):

    name = models.CharField(
        max_length=200,
    )

    icon = models.CharField(
        max_length=200,
        blank=True
        )

    team = models.ForeignKey(
        Company,
        null=True,
        on_delete=models.PROTECT,
    )

    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
    )

    datetime_created = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True,
    )

    slug = models.SlugField()

    def save(self, **kwargs):
        unique_slugify(self, self.name)
        super().save(**kwargs)
        self.created_by.companyuser.access.add(self)

    @models.permalink
    def get_absolute_url(self):
            return ("workspace:tab_detail", (), {
                "slug": self.slug
            })

    def __str__(self):
        return self.name

    def last_activity(self):
        threads = Thread.objects.filter(tab=self)

        if threads:
            thread = threads.latest("datetime")
            replies =  Reply.objects.filter(thread__in=threads)
            if replies:
                reply = replies.latest("datetime")
                if thread.datetime > reply.datetime:
                    return thread
                else:
                    return reply
            else:
                return thread
        else:
            return None

    @models.permalink
    def get_update_url(self):
        return ("workspace:tab_update", (), {
            "slug": self.slug,
        })

    @property
    def reveal(self):
        return "reveal_modal_tab" + str(self.pk)

    @property
    def form(self):
        from .forms import TabForm
        return TabForm(instance=self)


class Thread(models.Model):

    tab = models.ForeignKey(
        Tab,
        on_delete=models.CASCADE,
        )

    user = models.ForeignKey(
        User,
        related_name="created_by",
        on_delete=models.PROTECT,
    )

    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
    )

    title = models.CharField(
        max_length=200,
        null=True,
    )

    text = models.TextField(
        null=True,
    )

    assigned = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.PROTECT,
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
        null=True
        )

    last_updated = models.DateTimeField(
        null=True,
        auto_now=True,
    )

    slug = models.SlugField()

    @models.permalink
    def message_update_url(self):
        return ("workspace:thread_update_message", (), {
            "tab": self.tab.slug,
            "slug": self.slug
        })

    @models.permalink
    def get_absolute_url(self):
            return ("workspace:thread_detail", (), {
                "tab": self.tab.slug,
                "slug": self.slug
            })

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return str(self.tab) + ' - ' + str(self.title)

    @property
    def reveal(self):
        return "reveal_modal_thread" + str(self.pk)

    @property
    def revealSemetyText(self):
        return "reveal_modal_thread_semety" + str(self.pk)

    @property
    def form(self):
        from .forms import ThreadMessageForm
        return ThreadMessageForm(instance=self)

    def replies(self):
        return Reply.objects.filter(thread=self)

    def save(self, changed_last_update=False, **kwargs):
        if changed_last_update:
            self.changed_last_update = True
        else:
            self.changed_last_update = False
            unique_slugify(self, self.title)
        super().save(**kwargs)

    @property
    def files(self):
        return self.threadfile_set.all()

class Reply(models.Model):

    thread = models.ForeignKey(
        Thread,
        on_delete=models.CASCADE,
    )

    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
    )

    text = models.TextField(
        null=True,
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
        null=True
    )

    @property
    def form(self):
        from .forms import ReplyForm
        return ReplyForm(instance=self)

    @models.permalink
    def message_update_url(self):
        return ("workspace:reply_update", (), {
            "tab": self.thread.tab.slug,
            "thread": self.thread.slug,
            "pk": self.pk,

        })

    @property
    def revealSemetyText(self):
        return "reveal_modal_reply_semety" + str(self.pk)

    @property
    def reveal(self):
        return "reveal_modal_reply" + str(self.pk)

    @models.permalink
    def get_absolute_url(self):
            return ("workspace:thread_detail", (), {
                "tab": self.thread.tab.slug,
                "slug": self.thread.slug
            })

    @models.permalink
    def get_delete_url(self):
            return ("workspace:reply_delete", (), {
                "tab": self.thread.tab.slug,
                "thread": self.thread.slug,
                "pk": self.pk,
            })

    def save(self, **kwargs):
        super().save(**kwargs)
        self.thread.last_updated = self.datetime
        self.thread.save(changed_last_update=True)


class ThreadFile(models.Model):

    thread = models.ForeignKey(
        Thread,
        on_delete=models.CASCADE,
    )

    file = models.FileField(
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    datetime = models.DateTimeField(
        auto_now_add=True,
    )

@receiver(post_save, sender=Thread)
def thread_notification(sender, instance, created, **kwargs):
        from ..notifications.helpers import notify
        if not instance.changed_last_update:
            notify(user=instance.assigned, created=created, model="workspace_thread", model_instance=instance)


@receiver(post_save, sender=Reply)
def reply_notification(sender, instance, created, **kwargs):
        from ..notifications.helpers import notify
        notify(user=instance.thread.user, created=created, model="workspace_reply", model_instance=instance)
        notify(user=instance.thread.assigned, created=created, model="workspace_reply", model_instance=instance)

semety/apps/api/views.py
from django.shortcuts import render

# Create your views here.

semety/apps/clients/views.py
from .models import Client, Contact, ContactMemo
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView
from django.views.generic.edit import ModelFormMixin
from .forms import ClientForm, ContactForm, ContactMemoForm
from django.urls import reverse





def GetUser(teammate):
    return teammate.user

class ClientList(ListView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_add_form'] = ClientForm
        return context

    def get_queryset(self):
        return Client.objects.filter(team=self.request.user.company)


class ClientDetail(DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_edit_form'] = ClientForm(instance=self.object)
        context['add_contact_form'] = ContactForm
        return context


class ClientCreate(CreateView):
    model = Client
    form_class = ClientForm

    def form_valid(self, form):
        Form = form.save(commit=False)
        Form.user = self.request.user
        Form.team = self.request.user.company
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class ClientUpdate(UpdateView):
    model = Client
    form_class = ClientForm


class ClientDelete(DeleteView):
    model = Client

    def get_success_url(self):
        return reverse('clients:client_list', kwargs={})


#Contacts

class ContactDetail(DetailView):
    model = Contact

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['memo_form'] = ContactMemoForm
        context['contact_edit_form'] = ContactForm(instance=self.object)
        return context


class ContactDelete(DeleteView):
    model = Contact

    def get_success_url(self):
        return reverse('clients:client_detail', kwargs={'pk': self.kwargs['client']})


class ContactMemoUpdate(UpdateView):
    model = ContactMemo
    form_class = ContactMemoForm


class ContactMemoDelete(DeleteView):
    model = ContactMemo

    def get_success_url(self):
        return reverse('clients:contact_detail', kwargs={'client': self.kwargs['client'], 'pk': self.kwargs['contact']})


class ContactMemo(CreateView):
    model = ContactMemo
    form_class = ContactMemoForm

    def form_valid(self, form):
        Form = form.save(commit=False)
        Form.contact = Contact.objects.get(pk=self.kwargs['pk'])
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class ContactCreate(CreateView):
    model = Contact
    form_class = ContactForm

    def form_valid(self, form):
        Form = form.save(commit=False)
        Form.client = Client.objects.get(pk=self.kwargs['client'])
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class ContactUpdate(UpdateView):
    model = Contact
    form_class = ContactForm

semety/apps/notifications/views.py
from django.views.generic import ListView
from .models import Notification
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect

class NotificationList(ListView):
    model = Notification


def NotificationRead(request, pk):
    notification = get_object_or_404(
        Notification, user=request.user, id=pk)
    notification.read = True
    notification.save(send_email=False)

    return redirect(notification.model_instance.get_absolute_url())


def NotifcationMarkAllAsRead(request):
    for notifcation in Notification.objects.filter(user=request.user):
        notifcation.read = True
        notifcation.save(send_email=False)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

semety/utils/views.py
from django.views.generic import TemplateView


class FrontendView(TemplateView):
    def get_template_names(self, *args, **kwargs):
        # If no slug exists just serve the base so we can access the template switcher
        template_name = self.kwargs.get('slug', '_base')

        return ['frontend/{}.html'.format(template_name)]

semety/templates/workspace/reply_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete {{ tab.name }}</h1>
<form method="POST" action="">
    {% csrf_token %}
    <span class="error">Are you sure you want to delete?</span>

    <br><br>
    <input type="submit" class="button fill error" value="Confirm Delete" />
</form>
{% endblock content %}

semety/templates/workspace/reply_form.html
{% extends 'base.html' %}
{% block content %}
<h3>Reply to thread</h3>

<form action="" method="post">
{% csrf_token %}
{{ form.as_p}}
<input type="submit" value="Reply">
</form>
{% endblock %}

semety/templates/workspace/tab_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete {{ tab.name }}</h1>
<form method="POST" action="">
    {% csrf_token %}
    <span class="error">Are you sure you want to delete?</span>

    <br><br>
    <input type="submit" class="button fill error" value="Confirm Delete" />
</form>
{% endblock content %}

semety/templates/workspace/tab_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load humanize_custom %}
{% block breadcrumb %}
<li><a href="{% url "workspace:tab_list" %}">Workspace</a></li>
<li>{{ tab.name }}</li>
{% endblock breadcrumb %}
{% block content %}
{% url "workspace:thread_create" tab=tab.slug as thread_create %}
    {% include "workspace/modals/thread_form.html" with modalID="threadformModal" form=thread_form form_inline=thread_inline_form form_url=thread_create %}

    <div class="grid-x grid-padding-x">
        <div class="large-8 cell"><h1><small><i class="{% if tab.icon %}{{ tab.icon }}{% else %}fa fa-laptop{% endif %}"></i></small> {{ tab.name|title }}</h1></div>
        <div class="large-4 cell text-right">
            <a data-open="threadformModal" class="button">Add Thread</a>
        </div>

		<!--
		<div class="large-4 cell">
			<label for="">Search</label>
			<input type="text" placeholder="Thread name, file, people involved...">
		</div>
		<div class="large-3 cell">
			<label for="">Assigned</label>
			<select name="" id="">
				<option value="">---------</option>
			</select>
		</div>
		<div class="large-3 cell">
			<label for="">Published</label>
			<select name="" id="">
				<option value="">---------</option>
			</select>
		</div>
		<div class="large-2 cell">
			<input type="submit" class="large-12 cell search-button">
		</div>
		-->

        <div class="large-12 cell">
            <div class="tab-header form_item">
            <div class="grid-x">
            <div class="large-1 cell">
                {% if order_by == "status" %}
                    <a href="?order_by=status&order={% if order == "ascending" %}descending{% else %}ascending{% endif %}">
                        <i class="fa fa-circle nofa2 grey" aria-hidden="true"></i>
                        {% if order == "ascending" %}
                        <i class="fas fa-caret-down" aria-hidden="true"></i>
                        {% else %}
                        <i class="fas fa-caret-up" aria-hidden="true"></i>
                        {% endif %}
                    </a>
                {% else %}
                    <a href="?order_by=status">
                        <i class="fa fa-circle nofa2 grey" aria-hidden="true"></i>
                    </a>
                {% endif %}


            </div>

            <div class="large-3 cell">
                    {% include "workspace/includes/ordering.html" with filter_given="name" filter_name="Thread Name" order_by=order_by order=order %}
                </a>
            </div>
            <div class="large-2 cell">
                {% include "workspace/includes/ordering.html" with filter_given="assigned" filter_name="Assigned To" order_by=order_by order=order %}
            </div>
            <div class="large-2 cell">
                {% include "workspace/includes/ordering.html" with filter_given="replies" filter_name="Replies" order_by=order_by order=order %}
            </div>
            <div class="large-2 cell">
                {% include "workspace/includes/ordering.html" with filter_given="published" filter_name="Published" order_by=order_by order=order %}
            </div>
            <div class="large-2 cell">
                {% include "workspace/includes/ordering.html" with filter_given="last_updated" filter_name="Last Updated" order_by=order_by order=order %}
            </div>
        </div>
        </div>

        <ul class="tab-section">
            {% if not thread_list %}
                <li>
                    <div class="large-12 cell text-center no-results">No results found.</div>
                </li>
            {% endif %}
            {% for thread in thread_list %}
                <li>
                    <a href="{% url "workspace:thread_detail" tab.slug thread.slug %}" class="tab-name grid-x">
                        <div class="large-1 cell"><i class="fa fa-circle {{ thread.status.css_class_color }}" aria-hidden="true"></i></div>
                        <div class="large-3 cell">{{ thread.title }}</div>
                        <div class="large-2 cell">{% if thread.assigned == user %}{{ thread.assigned.get_full_name|truncatechars:18  }}{% else %} {{ thread.assigned.get_full_name|truncatechars:18  }}{% endif %}</div>
                        <div class="large-2 cell">{{ thread.replies.count }}</div>
                        <div class="large-2 cell">{{ thread.datetime|naturaltime_recent_only }}</div>
                        <div class="large-2 cell">{{ thread.last_updated|naturaltime_recent_only }}</div>
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="large-12 cell">
            <br>
        {% include "workspace/includes/pagination.html" with reply_list=thread_list %}
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="/static/js/semety_text.js"></script>
    <script src="/static/js/fontawesome-iconpicker.min.js"></script>
    <script>
        $('#id_icon').iconpicker();
        semetyText("#threadbox");
    </script>

{% endblock js %}

semety/templates/workspace/tab_form.html
{% extends 'base.html' %}
{% block content %}
<h3>Add Tab</h3>
<form action="" method="post">
	 {% csrf_token %}
{{ form.as_p}}
<input type="submit" value="Create" name="">
</form>
{% endblock %}

semety/templates/workspace/tab_list.html
{% extends 'base.html' %}
{% load humanize_custom %}
{% block breadcrumb %}
<li><a href="{% url "workspace:tab_list" %}">Workspace</a></li>
{% endblock breadcrumb %}
{% block content %}

    <div class="grid-x grid-padding-x">
        <div class="large-8 cell"><h1>Workspace</h1></div>
        <div class="large-4 cell text-right"><a href="{% url "workspace:tab_manage" %}" class="button">Manage Tabs</a></div>
    </div>

            {% if not tab_list %}
                <div class="grid-x grid-padding-x grid-padding-y">
                <div class="large-6 cell">
                        <div class="box_thread grid-x">
                            <div class="large-3 cell">
                                <i class="icon_lead fas fa-exclamation"></i>
                            </div>
                            <div class="large-6 cell">
                                <h4 class="box_thread_lead">No results found</h4>
                                <p>No tabs found.</p>
                            </div>

                        </div>
                </div>
            </div>
            {% endif %}
            <div class="grid-x grid-padding-x grid-padding-y">
                {% for tab in tab_list %}
                    <div class="large-6 cell">
                        <a href="{{ tab.get_absolute_url }}">
                            <div class="box_thread grid-x">
                                <div class="large-3 cell">
                                    <i class="icon_lead {% if tab.icon %}{{ tab.icon }}{% else %}fa fa-laptop{% endif %}"></i>
                                </div>
                                <div class="large-6 cell">
                                    <h4 class="box_thread_lead">{{ tab.name|title }} </h4>
                                    <p class="thread_update">{% if tab.last_activity %}Latest activity {{ tab.last_activity.datetime|naturaltime_recent_only }}{% else %}No Recent Activity{% endif %}</p>
                                </div>
                                <div class="large-3 cell thread_msgs">
                                    <h5><i class="fas fa-copy"></i> {{ tab.thread_set.all.count }}
                                    </h5>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

semety/templates/workspace/tab_manage.html
{% extends "base.html" %}
{% load humanize %}
{% load humanize_custom %}
{% block breadcrumb %}
<li><a href="{% url "workspace:tab_list" %}">Workspace</a></li>
<li>Manage Tabs</li>
{% endblock breadcrumb %}
{% block content %}
    {% url "workspace:tab_create" as tab_create %}
    {% include "workspace/modals/tab_form.html" with modalID="tabformModal" form=tab_form form_url=tab_create %}
    <div class="grid-x grid-padding-x">
        <div class="large-8 cell"><h1>Manage Tabs</h1></div>
        <div class="large-4 cell text-right">
            <a data-open="tabformModal" class="button">Add Tab</a>
        </div>

        {% for tab in tab_list %}
            {% include "workspace/modals/tab_form.html" with modalID=tab.reveal form=tab.form form_url=tab.get_update_url %}

        {% endfor %}

        <div class="large-12 cell">
            <div class="tab-header form_item">
            <div class="grid-x">
            <div class="large-2 cell">
                Icon
            </div>
            <div class="large-10 cell">
                Name
            </div>
        </div>
        </div>

        <ul class="tab-section">
            {% if not tab_list %}
                <li>
                    <div class="large-12 cell text-center no-results">No results found.</div>
                </li>
            {% endif %}
            {% for tab in tab_list %}
                <li>
                    <a data-open="{{ tab.reveal }}" class="tab-name grid-x">
                        <div class="large-2 cell"><i class="{{ tab.icon }}"></i></div>
                        <div class="large-10 cell">{{ tab.name }}</div>
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="large-12 cell">
            <br>

        </div>
    </div>
{% endblock %}
{% block js %}

    <script src="/static/js/fontawesome-iconpicker.min.js"></script>
    <script>
        $('#id_icon').iconpicker();
        icon_init($('#tabformModal'));
    </script>
{% for tab in tab_list %}
<script>
icon_init($('#{{ tab.reveal }}'));

</script>
{% endfor %}
{% endblock js %}

semety/templates/workspace/thread_detail.html
{% extends 'base.html' %}
{% block js %}
    <script src="/static/js/semety_text.js"></script>
    <script>
         semetyText("#semetyText");
         semetyText("#threadbox");

        semetyText("#{{ thread.revealSemetyText }}");
    {% for reply in reply_list %}
        semetyText("#{{ reply.revealSemetyText }}");
    {% endfor %}
    </script>
{% endblock js %}
{% block breadcrumb %}
<li><a href="{% url "workspace:tab_list" %}">Workspace</a></li>
<li><a href="{% url "workspace:tab_detail" slug=thread.tab.slug %}">{{ thread.tab.name }}</a></li>
<li>{{ thread.title }}</li>
{% endblock breadcrumb %}
{% block content %}
{% url "workspace:thread_update" tab=thread.tab.slug slug=thread.slug as thread_update %}
{% url "workspace:thread_delete" tab=thread.tab.slug slug=thread.slug as thread_delete %}
{% include "workspace/modals/thread_form.html" with modalID="threadformModal" form=thread_form form_inline=thread_inline_form form_url=thread_update form_delete_url=thread_delete %}
    <div class="grid-x grid-padding-x">
		<div class="large-8 cell"><h1>{{ thread.title|title }}</h1></div>
		<div class="large-4 cell text-right"><a data-open="threadformModal" class="button button-edit">Edit Thread</a></div>
        <div class="large-12 cell">
            <div class="grid-x main-content">
                <div class="large-12 cell">
                    <div class="large-12 cell tab-header form_item workspace-tab-header"  style="border-top-color:{{ thread.status.color }}">
                        <div class="grid-x">
                            <div class="large-10 cell">
                                <i class="thread-icon fa fa-circle {{ thread.status.css_class_color }}" aria-hidden="true"></i>
                                {{ thread.status|title }}
                            </div>
                            <div class="large-2 cell text-right">Page {{ reply_list.number }} of {{ reply_list.paginator.num_pages }}</div>
                        </div>
                    </div>
                    <div class="grid-x border thread_list">
						{% if thread.user.pk == request.user.pk %}
						{% include "workspace/includes/message_left.html" with thread=thread %}
						{% else %}
						{% include "workspace/includes/message_right.html" with thread=thread %}
						{% endif %}
						{% for reply in reply_list %}
						{% if reply.user.pk == request.user.pk %}
							{% include "workspace/includes/message_left.html" with thread=reply %}
						{% else %}
							{% include "workspace/includes/message_right.html" with thread=reply %}
						{% endif %}
						{% endfor %}

                    <div class="cell medium-12 large-6 large-offset-3">
                        <br>
                        {% include "workspace/includes/reply_form.html" with semetyText="semetyText" %}
                    </div>
                    <div class="large-12 cell">
                    {% include "workspace/includes/pagination.html" %}
                    <br>
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}